version: '2'

services:
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=my_db

  user-api:
    build: 
      context: ./user-api
    environment:
      - MONGO_URL=mongodb://mongoadmin:secret@mongo-db:27017/?retryWrites=true&w=majority
      - ADMIN_EMAIL=gspvsr@yahoo.com
    depends_on:
      - mongo-db

  admin-api:
    build: 
      context: ./admin-api
    environment:
      - MONGO_URL=mongodb://mongoadmin:secret@mongo-db:27017/?retryWrites=true&w=majority
    depends_on:
      - mongo-db

  user-ui:
    build: 
      context: ./user-api
    depends_on:
      - user-api

  admin-ui:
    build: 
      context: ./admin-ui
    depends_on:
      - admin-api

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-api
      - admin-api
      - user-ui
      - admin-ui
